### ISSUE TITLE
startup initialization 'Connection refused'

### ISSUE THREAD

**Issue by rbdubz3** [rbdubz3/sylvania-lightify-indigo#1]
startup error seen below:

20 Dec 2018 at 18:40:28
Installing and enabling plugin Sylvania Lightify v1.0.1
Loading plugin "Sylvania Lightify 1.0.1"
Starting plugin "Sylvania Lightify 1.0.1" (pid 34879)
Sylvania Lightify ..lightifyHubIpAddr=127.0.0.1
LightifyDirect ...Logging lightifydirect
Sylvania Lightify Error Error in plugin execution InitializeMain:

Traceback (most recent call last):
File "<string>", line 1, in <module>
File "plugin.py", line 46, in __init__
File "/Library/Application Support/Perceptive Automation/Indigo 7.2/Plugins/SylvaniaLightify.indigoPlugin/Contents/Server Plugin/lightifydirect.py", line 213, in __init__
File "/Library/Application Support/Perceptive Automation/Indigo 7.2/Plugins/SylvaniaLightify.indigoPlugin/Contents/Server Plugin/lightifydirect.py", line 218, in connect
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
error: (61, 'Connection refused')

Stopping plugin "Sylvania Lightify 1.0.1" (pid 34879)
Stopped plugin "Sylvania Lightify 1.0.1"

**Comment by rbdubz3** [comment]
improved initialization
